### CREATE

POST http://localhost:3000/api/program
Accept: application/json
Content-Type: application/json

{
  "name": "Belajar Go",
  "description": "Belajar Go sangat menyenangkan dan mudah"
}

### DETAILS

GET http://localhost:3000/api/program/100
Accept: application/json


### SEARCH

GET http://localhost:3000/api/program?q=belajar
Accept: application/json
Cache-Control: no-cache
